// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bymgpvefyasmgfgykixs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5bWdwdmVmeWFzbWdmZ3lraXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNDYzNDAsImV4cCI6MjA2MTcyMjM0MH0.a_avrO0htZ4XPaawRn4nRpgKvrlWSCWQhshjTQie0Mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);